---
title: "Article"
subtitle: "Inequality belief systems: what they look like, how to study them, and why they matter"
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    fig_caption: yes
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

```{r Setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE,
	fig.align="center",
	out.width='\\textwidth'
	)
```


# Input

## Packages 

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, qgraph, Matrix, igraph, sna, NetworkComparisonTest, bootnet,
       rio, foreign, matrixcalc, corclass, NetworkToolbox, conflicted, 
       EGAnet, texreg, ggpubr, lavaan, ltm, kableExtra, sjPlot, psych, nFactors,
       ggcorrplot, ggeffects, summarytools, GGally, ggnet2)

# if(!"devtools" %in% unlist(lapply(.libPaths(), list.files))){
#   install.packages("devtools")
# }
# devtools::load_all()
# options(buildtools.check = function(action) TRUE)
# devtools::install_github("hfgolino/EGAnet")
```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("labelled", "to_factor")
conflict_prefer("igraph", "compose")
conflict_prefer("igraph", "%s%")

#Options
options(max.print=999999)
options(scipen=999)
```

## Database

```{r}
#Load database
data = read_dta(here("Input", "data_full_stata.dta"))  %>% 
  clean_names()
```

# Processing

## Variables

```{r}

#Rename variables
data_con = data %>%
  rename(p_income = ineq_post1, 
         p_wealth = ineq_post2, 
         p_poor = ineq_post3, 
         p_black = ineq_post4,
         e_weafam = belief_1,
         e_edupar = belief_2,
         e_edu = belief_3,
         e_work = belief_4,
         e_people = belief_5,
         e_migra = belief_7,
         e_race = belief_6, 
         e_relig = belief_8,
         e_sex = belief_9,
         a_merit = ineq_pre1, 
         a_diversity = ineq_pre2, 
         a_equality = ineq_pre3,
         att_redist = ineq_post5)

#Select variables
data_con = data_con %>%
  select(nomem_encr, survey, country, treatment, 
         sex, agegroups, race, education, working, 
         hhincome, immigrant, marital, politics, religion,
         starts_with("p_"),
         starts_with("e_"),
         starts_with("a_"),
         starts_with("att_")) %>% 
  rename(gender = sex,
         age = agegroups,
         origin = immigrant,
         work_status = working,
         marital_status = marital)

#Recode variables
data_cat = data_con %>%
  mutate(gender = case_when(gender==1 ~ "Male",
                         gender==2 ~ "Female",
                         gender==0 ~ "Other",
                         TRUE ~NA),
         age = labelled::to_factor(age),
         origin = ifelse(origin==1, "Foreign-born", "Native-born"),
         race = ifelse(race==1, "White", "Other"),
         education = case_when(education<=2 ~ "High school or less",
                          education==3 ~ "Some college",
                          education>=4 ~ "College or more",
                          TRUE ~NA),
         work_status = ifelse(work_status==1, "Employed", "Not employed"),
         household_income = case_when(hhincome<=15000 ~ "Low",
                                     hhincome>15000 & hhincome<=70000 ~ "Medium",
                                     hhincome>70000 ~ "High",
                                     TRUE ~NA),
         marital_status = ifelse(marital_status==1, "Married", "Not married"),
         religion = case_when(religion==1 ~ "Protestant",
                              religion==2 ~ "Catholic",
                              religion==3 | religion==4 | religion==6 ~ "Other",
                              religion==5 | is.na(religion) ~ "None or not declared",
                              TRUE ~NA)
         )

#Levels
data_cat$gender <- factor(data_cat$gender,
                levels = c("Female", "Male", "Other"))

data_cat$origin <- factor(data_cat$origin,
                levels = c("Native-born", "Foreign-born"))

data_cat$race <- factor(data_cat$race,
                levels = c("Other", "White"))

data_cat$education <- factor(data_cat$education,
                levels = c("High school or less", "Some college", "College or more"))

data_cat$work_status <- factor(data_cat$work_status,
                levels = c("Not employed", "Employed"))

data_cat$household_income  <- factor(data_cat$household_income ,
                levels = c("Low", "Medium", "High"))

data_cat$marital_status <- factor(data_cat$marital_status,
                levels = c("Not married", "Married"))

data_cat$religion <- factor(data_cat$religion,
                levels = c("Catholic", "Protestant", "Other", "None or not declared"))

#Select variables
data_cat = data_cat %>% 
  select(nomem_encr, survey, country, treatment,
         gender, age, origin, race, education, 
         work_status, household_income, marital_status, politics, religion,
         p_income:att_redist)

#Check variables
skim(data_cat)
names(data_cat)

```


```{r}

#Filter US
data_us = data_cat %>% 
  filter(country==1) %>% 
  na.omit()

data_us_cca = data_us %>% 
  select(p_income:a_equality)

#Filter NL
data_nl = data_cat %>% 
  filter(country==2) %>% 
  na.omit()

data_nl_cca = data_nl %>% 
  select(p_income:a_equality)

```


## CCA

### US

```{r}

#CCA applied to ISSP US
cca_group_us <- cca(data_us_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass")) 

#Preliminary plots
us_plot_cca_1 = plot(cca_group_us, 1)
us_plot_cca_2 = plot(cca_group_us, 3)

```

```{r}
#Add membership to US
data_us_cca$cca = cca_group_us$membership
data_us$cca = cca_group_us$membership

#Filter out second CCA class and rename CCA groups
data_us = data_us %>% 
  filter(cca == 1 | cca == 3) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

data_us_cca = data_us_cca %>% 
  filter(cca == 1 | cca == 3) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

#Prepare CCA-driven dataframe for EGA
cca_us_1 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:a_equality)

cca_us_2 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:a_equality)

```

### NL

```{r}

#CCA applied to ISSP NL
cca_group_nl <- cca(data_nl_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#Preliminary plots
nl_plot_cca_1 = plot(cca_group_nl, 1)
nl_plot_cca_2 = plot(cca_group_nl, 4)

```

```{r}
#Add membership to NL
data_nl_cca$cca = cca_group_nl$membership
data_nl$cca = cca_group_nl$membership

#Filter out second CCA class and rename CCA groups
data_nl = data_nl %>% 
  filter(cca == 1 | cca == 4) %>% 
  mutate(cca = ifelse(cca=="4", 2, 1))

data_nl_cca = data_nl_cca %>% 
  filter(cca == 1 | cca == 4) %>% 
  mutate(cca = ifelse(cca=="4", 2, 1))

#Prepare CCA-driven dataframe for EGA
cca_nl_1 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:a_equality)

cca_nl_2 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:a_equality)


#Full sample
data_final = data_us %>% 
  bind_rows(data_nl)
  
frq(data, country)
frq(data_final, country)

```

## Correlation matrix

### US

```{r include=TRUE}
#Cor matrix
corr_us_1 <- round(cor(cca_us_1), 1)
corr_us_2 <- round(cor(cca_us_2), 1)

# Compute a matrix of correlation p-values
p.mat_us_1 <- cor_pmat(cca_us_1)
p.mat_us_2 <- cor_pmat(cca_us_2)

# Visualization
cor_m_us_1 = ggcorrplot(corr_us_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US1") +
  theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_2 = ggcorrplot(corr_us_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US2") +
  theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_1
cor_m_us_2
```

### NL

```{r include=TRUE}
#Cor matrix
corr_nl_1 <- round(cor(cca_nl_1), 1)
corr_nl_2 <- round(cor(cca_nl_2), 1)

# Compute a matrix of correlation p-values
p.mat_nl_1 <- cor_pmat(cca_nl_1)
p.mat_nl_2 <- cor_pmat(cca_nl_2)

# Visualization
cor_m_nl_1 = ggcorrplot(corr_nl_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL1") +
  theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_nl_2 = ggcorrplot(corr_nl_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL2") +
  theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_nl_1
cor_m_nl_2
```


```{r}
#Multiplot
plot_cor <- lapply(ls(pattern="^cor_m_"), function(x) get(x))
plot_cor <- plot_cor[c(3,4,1,2)]

g_plot_cor = ggarrange(plotlist = plot_cor, ncol = 2, nrow = 2) 

#Save
ggsave(here("Output", "Article", "Graphs", "cor_full.jpeg"),
       g_plot_cor, 
       dpi = 600,
       height = 12, width = 12
       )

```

## EGA

### US

```{r}
#EGA
set.seed(1)
ega_us_1 <- EGA(data=cca_us_1,  model = "glasso")

set.seed(1)
ega_us_2 <- EGA(data=cca_us_2,  model = "glasso")
```

### NL

```{r}
#EGA
set.seed(1)
ega_nl_1 <- EGA(data=cca_nl_1,  model = "glasso")

set.seed(1)
ega_nl_2 <- EGA(data=cca_nl_2,  model = "glasso")

```

### Plots

```{r}
list_data_egas <- lapply(ls(pattern="^ega_"), function(x) get(x))
list_data_egas <- list_data_egas[c(3,4,1,2)]
cca_groups = c("US1", "US2", "NL1", "NL2")
cca_groups_names = c("Uniformly integrated (US1)", 
                     "Contentiously integrated (US2)", 
                     "Uniformly compartimentalized (NL1)", 
                     "Contentiously compartimentalized (NL2)")
```

#### Standardized

```{r include=FALSE}
#Compare EGAs
comp_egas = compare.EGA.plots(
  input.list = list_data_egas,
  base = 1,
  labels = cca_groups,
  rows = 2, columns = 2,
  vsize = 15,
  node.alpha = 0.8,
  edge.alpha = 0.8,
  # edge.color = c("royalblue", "tomato"),
  legend.position = "none")

#Individual plots
plot_egastd_us1 = plot(comp_egas$individual[[1]]) +
      ggtitle(cca_groups_names[1]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_std_us1.jpg"), 
       plot_egastd_us1, height = 6, width = 6)


plot_egastd_us2 = plot(comp_egas$individual[[2]]) +
      ggtitle(cca_groups_names[2]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_std_us2.jpg"), 
       plot_egastd_us2, height = 6, width = 6)


plot_egastd_nl1 = plot(comp_egas$individual[[3]]) +
      ggtitle(cca_groups_names[3]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_std_nl1.jpg"), 
       plot_egastd_nl1, height = 6, width = 6)


plot_egastd_nl2 = plot(comp_egas$individual[[4]]) +
      ggtitle(cca_groups_names[4]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_std_nl2.jpg"), 
       plot_egastd_nl2, height = 6, width = 6)


#Full plot
# comp_egas_full = comp_egas$comparison.plot

plot_egas_std <- lapply(ls(pattern="^plot_egastd_"), function(x) get(x))
plot_egas_std <- plot_egas_std[c(3,4,1,2)]

g_plot_egas_std = ggarrange(plotlist = plot_egas_std, ncol = 2, nrow = 2) 


#Save
ggsave(here("Output", "Supplemental" , "EGA_multi_std.png"), 
       g_plot_egas_std, 
       height = 12, width = 12)
```

#### Non standardized

```{r}

#US1
plot_eganostd_us1 = plot(ega_us_1,
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15,
                    node.alpha = 0.8,
                    edge.alpha = 0.8,
                    color.palette = c("#D43728", "#91DDF1", "#C9D86F"),
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

plot_eganostd_us1 = plot_eganostd_us1  +
      ggtitle(cca_groups_names[1]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nostd_us1.jpg"), 
       plot_eganostd_us1, height = 6, width = 6)

#US2
plot_eganostd_us2 = plot(ega_us_2,
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15,
                    node.alpha = 0.8,
                    edge.alpha = 0.8,
                    color.palette = c("#D43728","#C9D86F", "#91DDF1"),
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

plot_eganostd_us2 = plot_eganostd_us2  +
      ggtitle(cca_groups_names[2]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nostd_us2.jpg"), 
       plot_eganostd_us2, height = 6, width = 6)

#NL1
plot_eganostd_nl1 = plot(ega_nl_1,
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15,
                    node.alpha = 0.8,
                    edge.alpha = 0.8,
                    color.palette = c("#D43728", "#91DDF1", "#C9D86F"),
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

plot_eganostd_nl1 = plot_eganostd_nl1  +
      ggtitle(cca_groups_names[3]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nostd_nl1.jpg"), 
       plot_eganostd_nl1, height = 6, width = 6)

#NL2
plot_eganostd_nl2 = plot(ega_nl_2,
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15,
                    node.alpha = 0.8,
                    edge.alpha = 0.8,
                    color.palette = c("#D43728", "#91DDF1", "#C9D86F"),
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

plot_eganostd_nl2 = plot_eganostd_nl2  +
      ggtitle(cca_groups_names[4]) +
      theme(plot.title = element_text(size=17, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nostd_nl2.jpg"), 
       plot_eganostd_us2, height = 6, width = 6)


#Full plot
# comp_egas_full = comp_egas$comparison.plot

plot_egas_nostd <- lapply(ls(pattern="^plot_eganostd_"), function(x) get(x))
plot_egas_nostd <- plot_egas_nostd[c(3,4,1,2)]

g_plot_egas_nostd = ggarrange(plotlist = plot_egas_nostd, ncol = 2, nrow = 2) 


#Save
ggsave(here("Output", "Article", "Graphs", "EGA_multi_nostd.jpeg"), 
       g_plot_egas_nostd, 
       dpi = 600,
       height = 12, width = 12
       )

```

## Sociodemographic Determinants of Inequality Belief Systems

```{r}

### US

### Dummy 0-1
data_us = data_us %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1))
         
#Regressions
m1_us_a = glm(cca_n ~ politics, data = data_us, family=binomial(link="logit"))
m2_us_a = glm(cca_n ~ gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_us, family=binomial(link="logit"))
m3_us_a = glm(cca_n ~ gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                religion, 
        data = data_us, family=binomial(link="logit"))
```


```{r}

### NL

### Dummy 0-1
data_nl = data_nl %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1))

#Regressions
m1_nl_a = glm(cca_n ~ politics, data = data_nl, family=binomial(link="logit"))
m2_nl_a = glm(cca_n ~ gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_nl, family=binomial(link="logit"))
m3_nl_a = glm(cca_n ~ gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                religion, 
        data = data_nl, family=binomial(link="logit"))
```

```{r}

#Output reduced
tab_model(list(m2_us_a, m2_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("US", "NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 2 & NL 2",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants.html")
)


#Output
tab_model(list(m1_us_a, m2_us_a, m3_us_a, m1_nl_a, m2_nl_a, m3_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US", "M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 2 & NL 2",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants_Extended.html")
)

```

```{r}
#Predicted values
ggpredict(m2_us_a)
ggpredict(m2_nl_a)

```



## Inequality Belief Systems and Support for Redistribution

### Graph

```{r}
#Full database
data_final = data_final %>% 
  mutate(country_r = ifelse(country==1, "US", "NL"),
         cca_full = case_when(country==1 & cca==1 ~ "Uniformly integrated (US1)",
                              country==1 & cca==2 ~ "Contentiously integrated (US2)",
                              country==2 & cca==1 ~ "Uniformly compartimentalized (NL1)",
                              country==2 & cca==2 ~ "Contentiously compartimentalized (NL2)"))

#Table
data_final %>% 
  select(cca_full, att_redist) %>% 
  flat_table(margin = "row", digits = 1)
  
#Graph
data_crosstab_us_nl = data_final %>%
  group_by(cca_full) %>% 
  mutate(n_cca = n()) %>%
  ungroup() %>% 
  group_by(cca_full, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1)

data_crosstab_us_nl$cca_full <- factor(data_crosstab_us_nl$cca_full,
                         levels = c("Uniformly integrated (US1)", 
                                    "Contentiously integrated (US2)", 
                                    "Uniformly compartimentalized (NL1)", 
                                    "Contentiously compartimentalized (NL2)"))

crosstab_us_nl = data_crosstab_us_nl %>%   
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca_full) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     limits = c(0,0.5)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Support for redistribution", y="Percentage") +
  theme_nice() +
  theme(strip.text = element_text(size=17, face="bold", colour = "black", hjust = 0.5),
        axis.text.y = element_text(size=15, colour = "grey20"), # Order: top, right, bottom, left
        axis.text.x = element_text(size=15, colour = "grey20"),
        axis.title = element_text(size=17, face = "plain", colour = "grey20"))

        
crosstab_us_nl

ggsave(here("Output", "Article", "Graphs", "redist_full.jpeg"), 
       crosstab_us_nl,
       dpi = 600,
       height = 12, width = 12
)

```

```{r}
data_final %>%
  group_by(cca_full) %>% 
  summarise(mean_justicia_ingreso = mean(att_redist)) 
```

### Regressions

```{r}
#EGA US
data_us_net = data_us %>% 
  select(p_income:a_equality)

set.seed(1)
US_ega = EGA(data=data_us_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#EGA NL
data_nl_net = data_nl %>% 
  select(p_income:a_equality)

set.seed(1)
NL_ega = EGA(data=data_nl_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#Indexes US
data_us = data_us %>% 
    mutate(index_views = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, a_diversity, a_equality))),
           index_factors = rowMeans(across(c(a_merit, e_work, e_edu, e_edupar, e_weafam, e_people))),
           index_identities = rowMeans(across(c(e_race, e_sex, e_relig, e_migra))))

#Indexes NL
data_nl = data_nl %>% 
    mutate(index_views = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, a_diversity, a_equality, a_merit))),
           index_factors = rowMeans(across(c(e_work, e_edu, e_edupar, e_weafam, e_people))),
           index_identities = rowMeans(across(c(e_race, e_sex, e_relig, e_migra))))

#Cronbach US
index_views_us = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, a_diversity, a_equality)

index_factors_us = data_us %>% 
  select(a_merit, e_weafam, e_edu, e_edupar, e_work, e_people)

index_identities_us = data_us %>% 
  select(e_race, e_migra, e_relig, e_sex)

a_us_1 = cronbach.alpha(index_views_us, CI=TRUE, standardized=TRUE) # 0.858
a_us_2 = cronbach.alpha(index_factors_us, CI=TRUE, standardized=TRUE) # 0.457
a_us_3 = cronbach.alpha(index_identities_us, CI=TRUE, standardized=TRUE) # 0.738

#Cronbach NL
index_views_nl = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, a_merit, a_diversity, a_equality)

index_factors_nl = data_us %>% 
  select(e_weafam, e_edu, e_edupar, e_work, e_people)

index_identities_nl = data_us %>% 
  select(e_race, e_migra, e_relig, e_sex)

a_nl_1 = cronbach.alpha(index_views_nl, CI=TRUE, standardized=TRUE) # 0.760
a_nl_2 = cronbach.alpha(index_factors_nl, CI=TRUE, standardized=TRUE) # 0.512
a_nl_3 = cronbach.alpha(index_identities_nl, CI=TRUE, standardized=TRUE) # 0.738

#Gather alphas and save
alphas = tibble(Index = c("index_views", "index_factors", "index_identities"),
                Alpha_US = round(c(a_us_1$alpha, a_us_2$alpha, a_us_3$alpha),3),
                Alpha_NL = round(c(a_nl_1$alpha, a_nl_2$alpha, a_nl_3$alpha),3))

#Save
save(alphas, file = here("Output",  "alphas.RData"))

```

```{r}
#Models

#US
m0_us_b = lm(att_redist ~ cca, data = data_us)
m1_us_b = lm(att_redist ~ index_views + index_factors + index_identities + gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_us)
m2_us_b = lm(att_redist ~ index_views + index_factors + index_identities + cca + gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_us)

#NL
m0_nl_b = lm(att_redist ~ cca, data = data_nl)
m1_nl_b = lm(att_redist ~ index_views + index_factors + index_identities + gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_nl)
m2_nl_b = lm(att_redist ~ index_views + index_factors + index_identities + cca + gender + age + origin + race + 
                education + work_status + household_income + marital_status + 
                politics + religion, data = data_nl)
```


```{r}

#Output
tab_model(list(m0_us_b, m1_us_b, m2_us_b), 
          #order.terms = c(1:5, 23, 6:22),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Linear regression models on support for redistribution - US",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Support_Redistribution_US.html")
)


tab_model(list(m0_nl_b, m1_nl_b, m2_nl_b), 
          #order.terms = c(1:5, 23, 6:22),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Linear regression models on support for redistribution - NL",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Support_Redistribution_NL.html")
)


```

## Descriptives on network centrality

### NL

```{r}
#Centrality
centralitynl1 = centrality(ega_nl_1$network)
centralitynl2 = centrality(ega_nl_2$network)
cent_nl = centralityPlot(GGM = list(NL1 = ega_nl_1$network, NL2 = ega_nl_2$network), standardized = FALSE, orderBy = "Strength")
ggsave(here("Output", "Supplemental", "cent_nl.jpg"), 
       cent_nl, height = 6, width = 6)
```
### US

```{r}
#Centrality
centralityus1 = centrality(ega_us_1$network)
centralityus2 = centrality(ega_us_2$network)
cent_us = centralityPlot(GGM = list(US1 = ega_us_1$network, US2 = ega_us_2$network), standardized = FALSE, orderBy = "Strength")
ggsave(here("Output", "Supplemental", "cent_us.jpg"), 
       cent_us, height = 6, width = 6)
```


# Output

## Databases

```{r}
#Save
save(data_final, data_us, data_us_cca, data_nl, data_nl_cca,
     file = here("Output",  "databases.RData"))

save(cca_us_1, cca_us_2, cca_nl_1, cca_nl_2,
     data_us_net, data_nl_net,
     ega_us_1, ega_us_2, ega_nl_1, ega_nl_2,
     US_ega, NL_ega,
     file = here("Output",  "databases_stability.RData"))
```

